//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlasSolar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Info {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Info() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtlasSolar.Resources.Info", typeof(Info).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Atlas.
        /// </summary>
        public static string AboutAtlas {
            get {
                return ResourceManager.GetString("AboutAtlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information in the Atlas of Solar Resources is presented in various forms - interactive maps, output tables and graphs:
        ///•	the resource maps – maps of long-term average annual values of solar radiation data;
        ///•	the maps for assessing the potential of solar energy – maps of monthly averages of different types of radiation on differently oriented surfaces, monthly averages of the geometric parameters of the Sun (altitude, azimuth);
        ///•	the climatic maps –  maps of basic meteorological characteristics;
        ///•	t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutAtlasText {
            get {
                return ResourceManager.GetString("AboutAtlasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the project.
        /// </summary>
        public static string AboutProject {
            get {
                return ResourceManager.GetString("AboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The concept of transition to a green economy, approved by Presidential Decree No. 577 of May 30, 2013, determined a list of priority tasks, mainly aimed at reforming certain sectors of the economy. As part of the transition to the Green Economy of the Republic of Kazakhstan, it is expected to increase the efficiency of the use of natural resources, improve the existing infrastructure and improve the well-being of the population. The project aims to assist in the practical implementation of the Concept for t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutProjectText {
            get {
                return ResourceManager.GetString("AboutProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Atlas of Solar Resources of Kazakhstan has been created within the framework of the Project of the Ministry of Energy of the Republic of Kazakhstan and the United Nations Development Program &quot;Support to the Government of the Republic of Kazakhstan in implementing the Concept of Transition to Green Economy and Institutionalization of the “Green Bridge” Partnership Program”..
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps of solar radiation indicators (direct, diffuse, total, etc.) constructed on the basis of climatic bases that are in open access (NASA SSE, Sustainable Buildings, SARAH-E).
        /// </summary>
        public static string Map1Description {
            get {
                return ResourceManager.GetString("Map1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar resources.
        /// </summary>
        public static string Map1Title {
            get {
                return ResourceManager.GetString("Map1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps of the main meteorological characteristics (air temperature, temperature of the underlying surface, cloudiness, atmospheric precipitation, albedo, etc.).
        /// </summary>
        public static string Map2Description {
            get {
                return ResourceManager.GetString("Map2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate.
        /// </summary>
        public static string Map2Title {
            get {
                return ResourceManager.GetString("Map2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps of factors affecting the potential of building solar power plants (specially protected natural areas, infrastructure, etc.).
        /// </summary>
        public static string Map3Description {
            get {
                return ResourceManager.GetString("Map3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factors affecting for the installation of grid-connected solar power stations.
        /// </summary>
        public static string Map3Title {
            get {
                return ResourceManager.GetString("Map3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A map of operating and projected solar energy facilities; a map of power lines.
        /// </summary>
        public static string Map4Description {
            get {
                return ResourceManager.GetString("Map4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar energy facilities.
        /// </summary>
        public static string Map4Title {
            get {
                return ResourceManager.GetString("Map4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Internet technologies and renewable sources will merge in the coming years”                            N. Nazarbayev.
        /// </summary>
        public static string Slogan1 {
            get {
                return ResourceManager.GetString("Slogan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transition to &quot;green&quot; energy and the introduction of &quot;green&quot; &lt;br /&gt;technologies is a growing vector of the global economy&lt;br/&gt;N. Nazarbayev.
        /// </summary>
        public static string Slogan2 {
            get {
                return ResourceManager.GetString("Slogan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Fifth challenge is the global energy security» N. Nazarbayev.
        /// </summary>
        public static string Slogan3 {
            get {
                return ResourceManager.GetString("Slogan3", resourceCulture);
            }
        }
    }
}
