//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlasSolar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtlasSolar.Resources.Layers", typeof(Layers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude agricultural lands (arable land, plantations, orchards).
        /// </summary>
        public static string AnalizeTerrainExcludeAgri {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeAgri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude the natural shrubby vegetations.
        /// </summary>
        public static string AnalizeTerrainExcludeBush {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeBush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude sands (including mobile and fixed grass and semi-shrub).
        /// </summary>
        public static string AnalizeTerrainExcludeDesert {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeDesert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude hydrographic objects (lakes, reservoirs, rivers, streams, flooded areas, swamps).
        /// </summary>
        public static string AnalizeTerrainExcludeHydro {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeHydro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude natural reserves.
        /// </summary>
        public static string AnalizeTerrainExcludeNatres {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeNatres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude natural parks.
        /// </summary>
        public static string AnalizeTerrainExcludePark {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludePark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude wildlife sanctuaries.
        /// </summary>
        public static string AnalizeTerrainExcludePreserve {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludePreserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude protected areas.
        /// </summary>
        public static string AnalizeTerrainExcludeProtect {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude natural reserves.
        /// </summary>
        public static string AnalizeTerrainExcludeReserve {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude human settlements.
        /// </summary>
        public static string AnalizeTerrainExcludeSettlement {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude solonchaks and sors.
        /// </summary>
        public static string AnalizeTerrainExcludeSolon {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeSolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude stony surfaces and placers, rock outcrops.
        /// </summary>
        public static string AnalizeTerrainExcludeStone {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude takyrs.
        /// </summary>
        public static string AnalizeTerrainExcludeTakyr {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeTakyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To exclude natural woody vegetation (forest, including saxaul, stlanik, woodlands).
        /// </summary>
        public static string AnalizeTerrainExcludeWood {
            get {
                return ResourceManager.GetString("AnalizeTerrainExcludeWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural areas (arable land, plantations, orchards) (AGRI).
        /// </summary>
        public static string FindTerrainAGRI {
            get {
                return ResourceManager.GetString("FindTerrainAGRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude, m (ALTITUDE).
        /// </summary>
        public static string FindTerrainALTITUDE {
            get {
                return ResourceManager.GetString("FindTerrainALTITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural scrub vegetation (BUSH).
        /// </summary>
        public static string FindTerrainBUSH {
            get {
                return ResourceManager.GetString("FindTerrainBUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sands (including mobile and fixed herbaceous and semi-shrubby) (DESERT).
        /// </summary>
        public static string FindTerrainDESERT {
            get {
                return ResourceManager.GetString("FindTerrainDESERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects hydrography (lakes, reservoirs, rivers, streams, flooded areas, swamps) (HYDRO).
        /// </summary>
        public static string FindTerrainHYDRO {
            get {
                return ResourceManager.GetString("FindTerrainHYDRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Reserves (NATRES).
        /// </summary>
        public static string FindTerrainNATRES {
            get {
                return ResourceManager.GetString("FindTerrainNATRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural parks (PARK).
        /// </summary>
        public static string FindTerrainPARK {
            get {
                return ResourceManager.GetString("FindTerrainPARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance to power lines, km (POWERDIST).
        /// </summary>
        public static string FindTerrainPOWERDIST {
            get {
                return ResourceManager.GetString("FindTerrainPOWERDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildlife sanctuaries (PRESERVE).
        /// </summary>
        public static string FindTerrainPRESERVE {
            get {
                return ResourceManager.GetString("FindTerrainPRESERVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected areas (PROTECT).
        /// </summary>
        public static string FindTerrainPROTECT {
            get {
                return ResourceManager.GetString("FindTerrainPROTECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar radiation of NASA, kW/m² per year (RADIATIONNASA).
        /// </summary>
        public static string FindTerrainRADIATIONNASA {
            get {
                return ResourceManager.GetString("FindTerrainRADIATIONNASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature reserves (RESERVE).
        /// </summary>
        public static string FindTerrainRESERVE {
            get {
                return ResourceManager.GetString("FindTerrainRESERVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance to motorways, km (ROADDIST).
        /// </summary>
        public static string FindTerrainROADDIST {
            get {
                return ResourceManager.GetString("FindTerrainROADDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance to settlements, km (SETTLEDIST).
        /// </summary>
        public static string FindTerrainSETTLEDIST {
            get {
                return ResourceManager.GetString("FindTerrainSETTLEDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory of settlements (SETTLEMENT).
        /// </summary>
        public static string FindTerrainSETTLEMENT {
            get {
                return ResourceManager.GetString("FindTerrainSETTLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slopes of terrain, degree (SLOPE).
        /// </summary>
        public static string FindTerrainSLOPE {
            get {
                return ResourceManager.GetString("FindTerrainSLOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solonchaks and sors (SOLON).
        /// </summary>
        public static string FindTerrainSOLON {
            get {
                return ResourceManager.GetString("FindTerrainSOLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocky surfaces and placers, rock outcrops (STONE).
        /// </summary>
        public static string FindTerrainSTONE {
            get {
                return ResourceManager.GetString("FindTerrainSTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takyrs (TAKYR).
        /// </summary>
        public static string FindTerrainTAKYR {
            get {
                return ResourceManager.GetString("FindTerrainTAKYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural woody vegetation (forest, including saxaul, woodland, woodlands) (WOOD).
        /// </summary>
        public static string FindTerrainWOOD {
            get {
                return ResourceManager.GetString("FindTerrainWOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure of slopes, compass headings.
        /// </summary>
        public static string Info_aspect_srtm {
            get {
                return ResourceManager.GetString("Info_aspect_srtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kWh/m²/month.
        /// </summary>
        public static string Info_avg_dnr_xx {
            get {
                return ResourceManager.GetString("Info_avg_dnr_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kWh/m²/year.
        /// </summary>
        public static string Info_avg_dnr_year {
            get {
                return ResourceManager.GetString("Info_avg_dnr_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaged Clear Sky Insolation Incident On A Horizontal Surface  (kWh/m²).
        /// </summary>
        public static string Info_clrskyavrg {
            get {
                return ResourceManager.GetString("Info_clrskyavrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Info_day_cld_22 {
            get {
                return ResourceManager.GetString("Info_day_cld_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Info_daylghtav {
            get {
                return ResourceManager.GetString("Info_daylghtav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuitable and useless land types.
        /// </summary>
        public static string Info_kzcover {
            get {
                return ResourceManager.GetString("Info_kzcover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The angle relative to the horizontal for which the monthly averaged total solar radiation is a maximum (degrees).
        /// </summary>
        public static string Info_OPTANG {
            get {
                return ResourceManager.GetString("Info_OPTANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string Info_rainavgesm {
            get {
                return ResourceManager.GetString("Info_rainavgesm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Radiation Incident On Tilted Surface (kWh/m²).
        /// </summary>
        public static string Info_retesh0mim {
            get {
                return ResourceManager.GetString("Info_retesh0mim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Radiation Incident On Tilted Surface (kWh/m²).
        /// </summary>
        public static string Info_rettlt0opt {
            get {
                return ResourceManager.GetString("Info_rettlt0opt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kWh/m².
        /// </summary>
        public static string Info_sis_klr {
            get {
                return ResourceManager.GetString("Info_sis_klr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain slope map, degrees.
        /// </summary>
        public static string Info_slope_srtm {
            get {
                return ResourceManager.GetString("Info_slope_srtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Surface Albedo (0 to 1.0).
        /// </summary>
        public static string Info_srfalbavg {
            get {
                return ResourceManager.GetString("Info_srfalbavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital relief model, m.
        /// </summary>
        public static string Info_srtm {
            get {
                return ResourceManager.GetString("Info_srtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Minimum Air Temperature At 10 m Above The Surface Of The Earth (°C).
        /// </summary>
        public static string Info_t10m_min {
            get {
                return ResourceManager.GetString("Info_t10m_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Maximum Air Temperature At 10 m Above The Surface Of The Earth (°C).
        /// </summary>
        public static string Info_t10mmax {
            get {
                return ResourceManager.GetString("Info_t10mmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Earth Skin Temperature (°C).
        /// </summary>
        public static string Info_tskinavg {
            get {
                return ResourceManager.GetString("Info_tskinavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monuments of archeology and culture.
        /// </summary>
        public static string Legend_arheopamyat_1 {
            get {
                return ResourceManager.GetString("Legend_arheopamyat_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard zones of monuments of archeology and culture.
        /// </summary>
        public static string Legend_arheopamyat_2 {
            get {
                return ResourceManager.GetString("Legend_arheopamyat_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure of slopes, compass headings.
        /// </summary>
        public static string Legend_aspect_srtm {
            get {
                return ResourceManager.GetString("Legend_aspect_srtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Normal Radiation (source - NASA SSE), кWh/m²/month.
        /// </summary>
        public static string Legend_avg_dnr_xx {
            get {
                return ResourceManager.GetString("Legend_avg_dnr_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Normal Radiation (source - NASA SSE), кWh/m²/year.
        /// </summary>
        public static string Legend_avg_dnr_year {
            get {
                return ResourceManager.GetString("Legend_avg_dnr_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average monthly value of the atmospheric transparency index (from 0 to 1.0).
        /// </summary>
        public static string Legend_avg_kt_22 {
            get {
                return ResourceManager.GetString("Legend_avg_kt_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average monthly normalized value of the atmospheric transparency index (from 0 to 1.0).
        /// </summary>
        public static string Legend_avg_nkt_22 {
            get {
                return ResourceManager.GetString("Legend_avg_nkt_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaged Clear Sky Insolation Incident On A Horizontal Surface  (kWh/m²/month).
        /// </summary>
        public static string Legend_clrskyavrg_xx {
            get {
                return ResourceManager.GetString("Legend_clrskyavrg_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaged Clear Sky Insolation Incident On A Horizontal Surface  (kWh/m²/year).
        /// </summary>
        public static string Legend_clrskyavrg_year {
            get {
                return ResourceManager.GetString("Legend_clrskyavrg_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average monthly daytime cloud cover (%).
        /// </summary>
        public static string Legend_day_cld_22 {
            get {
                return ResourceManager.GetString("Legend_day_cld_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average monthly duration of daylight hours (hours).
        /// </summary>
        public static string Legend_daylghtav {
            get {
                return ResourceManager.GetString("Legend_daylghtav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly averaged Direct Normal Irradiance at surface (DNI) (kWh/m²).
        /// </summary>
        public static string Legend_dni_xx {
            get {
                return ResourceManager.GetString("Legend_dni_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Direct Normal Irradiance at surface (DNI) (kWh/m²).
        /// </summary>
        public static string Legend_dni_year {
            get {
                return ResourceManager.GetString("Legend_dni_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuse radiation (source - NASA SSE), кWh/m²/month.
        /// </summary>
        public static string Legend_exp_dif_xx {
            get {
                return ResourceManager.GetString("Legend_exp_dif_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuse radiation (source - NASA SSE), кWh/m²/year.
        /// </summary>
        public static string Legend_exp_dif_year {
            get {
                return ResourceManager.GetString("Legend_exp_dif_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrography and water protection zones.
        /// </summary>
        public static string Legend_hidroohrzony_1 {
            get {
                return ResourceManager.GetString("Legend_hidroohrzony_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security zones of hydrography and water protection zones.
        /// </summary>
        public static string Legend_hidroohrzony_2 {
            get {
                return ResourceManager.GetString("Legend_hidroohrzony_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuitable and useless land types.
        /// </summary>
        public static string Legend_kzcover {
            get {
                return ResourceManager.GetString("Legend_kzcover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to territories of settlements.
        /// </summary>
        public static string Legend_kzcover_1 {
            get {
                return ResourceManager.GetString("Legend_kzcover_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agricultural areas (arable land, plantations, gardens).
        /// </summary>
        public static string Legend_kzcover_2 {
            get {
                return ResourceManager.GetString("Legend_kzcover_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to natural woody vegetation (forest, including saxaul, elfin wood, woodlands).
        /// </summary>
        public static string Legend_kzcover_3 {
            get {
                return ResourceManager.GetString("Legend_kzcover_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to natural shrubby vegetation.
        /// </summary>
        public static string Legend_kzcover_4 {
            get {
                return ResourceManager.GetString("Legend_kzcover_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hydrography objects (lakes, reservoirs, rivers, streams, flooding areas, swamps).
        /// </summary>
        public static string Legend_kzcover_5 {
            get {
                return ResourceManager.GetString("Legend_kzcover_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takyrs.
        /// </summary>
        public static string Legend_kzcover_6 {
            get {
                return ResourceManager.GetString("Legend_kzcover_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sands (including mobile and fixed herbaceous and semi-shrubby.
        /// </summary>
        public static string Legend_kzcover_7 {
            get {
                return ResourceManager.GetString("Legend_kzcover_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salines and sors.
        /// </summary>
        public static string Legend_kzcover_8 {
            get {
                return ResourceManager.GetString("Legend_kzcover_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rocky surfaces and alluvials, outcrops.
        /// </summary>
        public static string Legend_kzcover_9 {
            get {
                return ResourceManager.GetString("Legend_kzcover_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specially Protected Natural Areas.
        /// </summary>
        public static string Legend_oopt {
            get {
                return ResourceManager.GetString("Legend_oopt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State nature monuments .
        /// </summary>
        public static string Legend_pamyatnikprirodypol_1 {
            get {
                return ResourceManager.GetString("Legend_pamyatnikprirodypol_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer zone of state nature monuments.
        /// </summary>
        public static string Legend_pamyatnikprirodypol_2 {
            get {
                return ResourceManager.GetString("Legend_pamyatnikprirodypol_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State national nature parks and their protection zones.
        /// </summary>
        public static string Legend_prirparki_1 {
            get {
                return ResourceManager.GetString("Legend_prirparki_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected areas of state national natural parks.
        /// </summary>
        public static string Legend_prirparki_2 {
            get {
                return ResourceManager.GetString("Legend_prirparki_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Amount of Precipitation (mm/month).
        /// </summary>
        public static string Legend_rainavgesm_xx {
            get {
                return ResourceManager.GetString("Legend_rainavgesm_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Amount of Precipitation (mm/year).
        /// </summary>
        public static string Legend_rainavgesm_year {
            get {
                return ResourceManager.GetString("Legend_rainavgesm_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Radiation Incident On Tilted Surface (kWh/m²/month).
        /// </summary>
        public static string Legend_retesh0mim_xx {
            get {
                return ResourceManager.GetString("Legend_retesh0mim_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Radiation Incident On Tilted Surface (kWh/m²/year).
        /// </summary>
        public static string Legend_retesh0mim_year {
            get {
                return ResourceManager.GetString("Legend_retesh0mim_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Radiation Incident On Tilted Surface (kWh/m²/month).
        /// </summary>
        public static string Legend_rettlt0opt_xx {
            get {
                return ResourceManager.GetString("Legend_rettlt0opt_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Radiation Incident On Tilted Surface (kWh/m²/year).
        /// </summary>
        public static string Legend_rettlt0opt_year {
            get {
                return ResourceManager.GetString("Legend_rettlt0opt_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State nature reserves and their protection zones..
        /// </summary>
        public static string Legend_rezervaty_1 {
            get {
                return ResourceManager.GetString("Legend_rezervaty_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected areas of state nature reserves.
        /// </summary>
        public static string Legend_rezervaty_2 {
            get {
                return ResourceManager.GetString("Legend_rezervaty_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly averaged Total Radiation under the clear sky (SIC) (kWh/m²).
        /// </summary>
        public static string Legend_sic_xx {
            get {
                return ResourceManager.GetString("Legend_sic_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Total Radiation under the clear sky (SIC) (kWh/m²).
        /// </summary>
        public static string Legend_sic_year {
            get {
                return ResourceManager.GetString("Legend_sic_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly averaged Surface Incoming Direct Irradiance (SID) (kWh/m²).
        /// </summary>
        public static string Legend_sid_xx {
            get {
                return ResourceManager.GetString("Legend_sid_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Surface Incoming Direct Irradiance (SID) (kWh/m²).
        /// </summary>
        public static string Legend_sid_year {
            get {
                return ResourceManager.GetString("Legend_sid_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Surface Incoming  Irradiance (SIS) (kWh/m²/month).
        /// </summary>
        public static string Legend_sis_klr_xx {
            get {
                return ResourceManager.GetString("Legend_sis_klr_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Surface Incoming  Irradiance (SIS) (kWh/m²/year).
        /// </summary>
        public static string Legend_sis_klr_year {
            get {
                return ResourceManager.GetString("Legend_sis_klr_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly averaged Surface Incoming Irradiance (SIS) (kWh/m²).
        /// </summary>
        public static string Legend_sis_xx {
            get {
                return ResourceManager.GetString("Legend_sis_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Surface Incoming  Irradiance (SIS) (kWh/m²).
        /// </summary>
        public static string Legend_sis_year {
            get {
                return ResourceManager.GetString("Legend_sis_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain slope map, degrees.
        /// </summary>
        public static string Legend_slope_srtm {
            get {
                return ResourceManager.GetString("Legend_slope_srtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Surface Albedo (0 to 1.0).
        /// </summary>
        public static string Legend_srfalbavg_xx {
            get {
                return ResourceManager.GetString("Legend_srfalbavg_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height above sea level, m.
        /// </summary>
        public static string Legend_srtm {
            get {
                return ResourceManager.GetString("Legend_srtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Insolation Incident On A Horizontal Surface (source - NASA SSE), kWh/m²/month.
        /// </summary>
        public static string Legend_swv_dwn_xx {
            get {
                return ResourceManager.GetString("Legend_swv_dwn_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Insolation Incident On A Horizontal Surface (source - NASA SSE), kWh/m²/year.
        /// </summary>
        public static string Legend_swv_dwn_year {
            get {
                return ResourceManager.GetString("Legend_swv_dwn_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Minimum Air Temperature At 10 m Above The Surface Of The Earth (°C).
        /// </summary>
        public static string Legend_t10m_min_xx {
            get {
                return ResourceManager.GetString("Legend_t10m_min_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average monthly air temperature (source - NASA SSE), °С.
        /// </summary>
        public static string Legend_t10m_xx {
            get {
                return ResourceManager.GetString("Legend_t10m_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Maximum Air Temperature At 10 m Above The Surface Of The Earth (°C).
        /// </summary>
        public static string Legend_t10mmax_xx {
            get {
                return ResourceManager.GetString("Legend_t10mmax_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Earth Skin Temperature (°C).
        /// </summary>
        public static string Legend_tskinavg_xx {
            get {
                return ResourceManager.GetString("Legend_tskinavg_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State nature sanctuaries .
        /// </summary>
        public static string Legend_zakazniky_1 {
            get {
                return ResourceManager.GetString("Legend_zakazniky_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected areas of state nature reserves.
        /// </summary>
        public static string Legend_zakazniky_2 {
            get {
                return ResourceManager.GetString("Legend_zakazniky_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural reserves and their protection zones.
        /// </summary>
        public static string Legend_zapovedniki_1 {
            get {
                return ResourceManager.GetString("Legend_zapovedniki_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected areas of reserves.
        /// </summary>
        public static string Legend_zapovedniki_2 {
            get {
                return ResourceManager.GetString("Legend_zapovedniki_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State preserved areas.
        /// </summary>
        public static string Legend_zapovedzony_1 {
            get {
                return ResourceManager.GetString("Legend_zapovedzony_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected areas of state protected areas.
        /// </summary>
        public static string Legend_zapovedzony_2 {
            get {
                return ResourceManager.GetString("Legend_zapovedzony_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power lines.
        /// </summary>
        public static string lep {
            get {
                return ResourceManager.GetString("lep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection zones of power lines.
        /// </summary>
        public static string lep_bufer {
            get {
                return ResourceManager.GetString("lep_bufer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power lines, V.
        /// </summary>
        public static string lep_legend {
            get {
                return ResourceManager.GetString("lep_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Lines (Secondary).
        /// </summary>
        public static string lep2 {
            get {
                return ResourceManager.GetString("lep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Lines (Secondary), V.
        /// </summary>
        public static string lep2_legend {
            get {
                return ResourceManager.GetString("lep2_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar power stations.
        /// </summary>
        public static string MapAuxiliary {
            get {
                return ResourceManager.GetString("MapAuxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate.
        /// </summary>
        public static string MapClimate {
            get {
                return ResourceManager.GetString("MapClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factors affecting the building of grid-connected solar power stations.
        /// </summary>
        public static string MapFactors {
            get {
                return ResourceManager.GetString("MapFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar resources.
        /// </summary>
        public static string MapsResources {
            get {
                return ResourceManager.GetString("MapsResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather stations.
        /// </summary>
        public static string meteo_st {
            get {
                return ResourceManager.GetString("meteo_st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northeast.
        /// </summary>
        public static string Northeast {
            get {
                return ResourceManager.GetString("Northeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest.
        /// </summary>
        public static string Northwest {
            get {
                return ResourceManager.GetString("Northwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Areas.
        /// </summary>
        public static string oblasti {
            get {
                return ResourceManager.GetString("oblasti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Clear Sky Insolation Incident On A Horizontal Surface  (kWh/m²).
        /// </summary>
        public static string p_clr_cky {
            get {
                return ResourceManager.GetString("p_clr_cky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Insolation Incident On A Horizontal Surface  (kWh/m²).
        /// </summary>
        public static string p_swv_dwn {
            get {
                return ResourceManager.GetString("p_swv_dwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sums of the average monthly solar radiation arriving at the upper atmosphere boundary (kWh/m²).
        /// </summary>
        public static string p_toa_dwn {
            get {
                return ResourceManager.GetString("p_toa_dwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane.
        /// </summary>
        public static string Plane {
            get {
                return ResourceManager.GetString("Plane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected.
        /// </summary>
        public static string Projected {
            get {
                return ResourceManager.GetString("Projected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relief.
        /// </summary>
        public static string Relief {
            get {
                return ResourceManager.GetString("Relief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southeast.
        /// </summary>
        public static string Southeast {
            get {
                return ResourceManager.GetString("Southeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southwest.
        /// </summary>
        public static string Southwest {
            get {
                return ResourceManager.GetString("Southwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar power stations.
        /// </summary>
        public static string spp {
            get {
                return ResourceManager.GetString("spp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monuments of archeology and culture.
        /// </summary>
        public static string Tree_arheopamyat {
            get {
                return ResourceManager.GetString("Tree_arheopamyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure of slopes, compass headings  .
        /// </summary>
        public static string Tree_aspect_srtm {
            get {
                return ResourceManager.GetString("Tree_aspect_srtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Direct Normal Radiation (kWh/m²).
        /// </summary>
        public static string Tree_avg_dnr {
            get {
                return ResourceManager.GetString("Tree_avg_dnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average monthly value of the atmospheric transparency index (from 0 to 1.0).
        /// </summary>
        public static string Tree_avg_kt_22 {
            get {
                return ResourceManager.GetString("Tree_avg_kt_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average monthly normalized value of the atmospheric transparency index (from 0 to 1.0).
        /// </summary>
        public static string Tree_avg_nkt_22 {
            get {
                return ResourceManager.GetString("Tree_avg_nkt_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Clear Sky Insolation Incident On A Horizontal Surface  (kWh/m²).
        /// </summary>
        public static string Tree_clrskyavrg {
            get {
                return ResourceManager.GetString("Tree_clrskyavrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average monthly daytime cloud cover (%).
        /// </summary>
        public static string Tree_day_cld_22 {
            get {
                return ResourceManager.GetString("Tree_day_cld_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average monthly duration of daylight hours (hours).
        /// </summary>
        public static string Tree_daylghtav {
            get {
                return ResourceManager.GetString("Tree_daylghtav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Direct Normal Irradiance at surface (DNI) (kWh/m²).
        /// </summary>
        public static string Tree_dni {
            get {
                return ResourceManager.GetString("Tree_dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Diffuse Radiation Incident On A Horizontal Surface  (kWh/m²).
        /// </summary>
        public static string Tree_exp_dif {
            get {
                return ResourceManager.GetString("Tree_exp_dif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrography and water protection zones.
        /// </summary>
        public static string Tree_hidroohrzony {
            get {
                return ResourceManager.GetString("Tree_hidroohrzony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuitable and little avail
        /// land types.
        /// </summary>
        public static string Tree_kzcover {
            get {
                return ResourceManager.GetString("Tree_kzcover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specially Protected Natural Areas.
        /// </summary>
        public static string Tree_oopt {
            get {
                return ResourceManager.GetString("Tree_oopt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural monuments of nature.
        /// </summary>
        public static string Tree_pamyatnikprirodypol {
            get {
                return ResourceManager.GetString("Tree_pamyatnikprirodypol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Parks.
        /// </summary>
        public static string Tree_prirparki {
            get {
                return ResourceManager.GetString("Tree_prirparki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaged Amount of Precipitation (mm).
        /// </summary>
        public static string Tree_rainavgesm {
            get {
                return ResourceManager.GetString("Tree_rainavgesm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Radiation Incident On Tilted Surface (kWh/m²).
        /// </summary>
        public static string Tree_retesh0mim {
            get {
                return ResourceManager.GetString("Tree_retesh0mim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Radiation Incident On Tilted Surface (kWh/m²).
        /// </summary>
        public static string Tree_rettlt0opt {
            get {
                return ResourceManager.GetString("Tree_rettlt0opt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Reserves.
        /// </summary>
        public static string Tree_rezervaty {
            get {
                return ResourceManager.GetString("Tree_rezervaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Clear Sky Insolation Incident On A Horizontal Surface (SIC) (kWh/m²).
        /// </summary>
        public static string Tree_sic {
            get {
                return ResourceManager.GetString("Tree_sic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Direct Horizontal Irradiance at surface  (SID) (kWh/m²).
        /// </summary>
        public static string Tree_sid {
            get {
                return ResourceManager.GetString("Tree_sid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Surface Incoming  Irradiance (SIS) (kWh/m²).
        /// </summary>
        public static string Tree_sis {
            get {
                return ResourceManager.GetString("Tree_sis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Surface Incoming  Irradiance (SIS) (kWh/m²).
        /// </summary>
        public static string Tree_sis_klr {
            get {
                return ResourceManager.GetString("Tree_sis_klr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain slope map.
        /// </summary>
        public static string Tree_slope_srtm {
            get {
                return ResourceManager.GetString("Tree_slope_srtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Surface Albedo (0 to 1.0).
        /// </summary>
        public static string Tree_srfalbavg {
            get {
                return ResourceManager.GetString("Tree_srfalbavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height above sea level.
        /// </summary>
        public static string Tree_srtm {
            get {
                return ResourceManager.GetString("Tree_srtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Insolation Incident On A Horizontal Surface  (kWh/m²).
        /// </summary>
        public static string Tree_swv_dwn {
            get {
                return ResourceManager.GetString("Tree_swv_dwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Air Temperature At 10 m Above The Surface Of The Earth (°C).
        /// </summary>
        public static string Tree_t10m {
            get {
                return ResourceManager.GetString("Tree_t10m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Minimum Air Temperature At 10 m Above The Surface Of The Earth (°C).
        /// </summary>
        public static string Tree_t10m_min {
            get {
                return ResourceManager.GetString("Tree_t10m_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Maximum Air Temperature At 10 m Above The Surface Of The Earth (°C).
        /// </summary>
        public static string Tree_t10mmax {
            get {
                return ResourceManager.GetString("Tree_t10mmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Averaged Earth Skin Temperature (°C).
        /// </summary>
        public static string Tree_tskinavg {
            get {
                return ResourceManager.GetString("Tree_tskinavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural wildlife sanctuaries.
        /// </summary>
        public static string Tree_zakazniky {
            get {
                return ResourceManager.GetString("Tree_zakazniky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural reserves.
        /// </summary>
        public static string Tree_zapovedniki {
            get {
                return ResourceManager.GetString("Tree_zapovedniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural protected areas.
        /// </summary>
        public static string Tree_zapovedzony {
            get {
                return ResourceManager.GetString("Tree_zapovedzony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
    }
}
